num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
num3 = float(input("Enter the third number: "))
max_num = max(num1, num2, num3)
print(f"The maximum of {num1}, {num2}, and {num3} is {max_num}")
